################################################################################
# Automatically-generated file. Do not edit!
################################################################################

OBJ_SRCS := 
ASM_SRCS := 
C_SRCS := 
O_SRCS := 
S_UPPER_SRCS := 
EXECUTABLES := 
OBJS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
src/TSRM \
src/Zend \
src/ext/bcmath/.libs \
src/ext/bcmath \
src/ext/bcmath/libbcmath/src/.libs \
src/ext/bcmath/libbcmath/src \
src/ext/bz2 \
src/ext/calendar \
src/ext/com_dotnet \
src/ext/ctype \
src/ext/curl \
src/ext/date/lib \
src/ext/date \
src/ext/dba \
src/ext/dba/libcdb \
src/ext/dba/libflatfile \
src/ext/dba/libinifile \
src/ext/dom \
src/ext/enchant \
src/ext/ereg \
src/ext/ereg/regex \
src/ext/exif \
src/ext/fileinfo \
src/ext/fileinfo/libmagic \
src/ext/filter \
src/ext/ftp \
src/ext/gd \
src/ext/gd/libgd \
src/ext/gettext \
src/ext/gmp \
src/ext/hash \
src/ext/iconv \
src/ext/imap \
src/ext/interbase \
src/ext/intl/collator \
src/ext/intl/common \
src/ext/intl/converter \
src/ext/intl/dateformat \
src/ext/intl/formatter \
src/ext/intl/grapheme \
src/ext/intl/idn \
src/ext/intl \
src/ext/intl/locale \
src/ext/intl/msgformat \
src/ext/intl/normalizer \
src/ext/intl/resourcebundle \
src/ext/intl/spoofchecker \
src/ext/intl/transliterator \
src/ext/json \
src/ext/ldap \
src/ext/libxml \
src/ext/lion/.libs \
src/ext/lion \
src/ext/mbstring/libmbfl/filters \
src/ext/mbstring/libmbfl/mbfl \
src/ext/mbstring/libmbfl/nls \
src/ext/mbstring/libmbfl/tests \
src/ext/mbstring/libmbfl/tests/conv_encoding.tests \
src/ext/mbstring \
src/ext/mbstring/oniguruma/enc \
src/ext/mbstring/oniguruma \
src/ext/mbstring/oniguruma/win32 \
src/ext/mbstring/ucgendat \
src/ext/mcrypt \
src/ext/mssql \
src/ext/mysql \
src/ext/mysqli \
src/ext/mysqlnd \
src/ext/oci8 \
src/ext/odbc \
src/ext/opcache/Optimizer \
src/ext/opcache \
src/ext/openssl \
src/ext/pcntl \
src/ext/pcre/pcrelib \
src/ext/pcre \
src/ext/pdo \
src/ext/pdo_dblib \
src/ext/pdo_firebird \
src/ext/pdo_mysql \
src/ext/pdo_oci \
src/ext/pdo_odbc \
src/ext/pdo_pgsql \
src/ext/pdo_sqlite \
src/ext/pgsql \
src/ext/phar \
src/ext/posix \
src/ext/pspell \
src/ext/readline \
src/ext/recode \
src/ext/reflection \
src/ext/session \
src/ext/shmop \
src/ext/simplexml \
src/ext/skeleton \
src/ext/snmp \
src/ext/soap \
src/ext/sockets \
src/ext/spl \
src/ext/sqlite3/libsqlite \
src/ext/sqlite3 \
src/ext/standard \
src/ext/sybase_ct \
src/ext/sysvmsg \
src/ext/sysvsem \
src/ext/sysvshm \
src/ext/tidy \
src/ext/tokenizer \
src/ext/wddx \
src/ext/xml \
src/ext/xmlreader \
src/ext/xmlrpc/libxmlrpc \
src/ext/xmlrpc \
src/ext/xmlwriter \
src/ext/xsl \
src/ext/zip/lib \
src/ext/zip \
src/ext/zlib \
src/main \
src/main/streams \
src/netware \
src/sapi/aolserver \
src/sapi/apache \
src/sapi/apache2filter \
src/sapi/apache2handler \
src/sapi/apache_hooks \
src/sapi/caudium \
src/sapi/cgi \
src/sapi/cli \
src/sapi/continuity \
src/sapi/embed \
src/sapi/fpm/fpm/events \
src/sapi/fpm/fpm \
src/sapi/isapi \
src/sapi/isapi/stresstest \
src/sapi/litespeed \
src/sapi/milter \
src/sapi/nsapi \
src/sapi/phttpd \
src/sapi/pi3web \
src/sapi/roxen \
src/sapi/thttpd \
src/sapi/tux \
src/sapi/webjames \
src \
src/win32/build \
src/win32 \

