################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../src/ext/standard/array.c \
../src/ext/standard/assert.c \
../src/ext/standard/base64.c \
../src/ext/standard/basic_functions.c \
../src/ext/standard/browscap.c \
../src/ext/standard/crc32.c \
../src/ext/standard/credits.c \
../src/ext/standard/crypt.c \
../src/ext/standard/crypt_blowfish.c \
../src/ext/standard/crypt_freesec.c \
../src/ext/standard/crypt_sha256.c \
../src/ext/standard/crypt_sha512.c \
../src/ext/standard/css.c \
../src/ext/standard/cyr_convert.c \
../src/ext/standard/datetime.c \
../src/ext/standard/dir.c \
../src/ext/standard/dl.c \
../src/ext/standard/dns.c \
../src/ext/standard/dns_win32.c \
../src/ext/standard/exec.c \
../src/ext/standard/file.c \
../src/ext/standard/filestat.c \
../src/ext/standard/filters.c \
../src/ext/standard/flock_compat.c \
../src/ext/standard/formatted_print.c \
../src/ext/standard/fsock.c \
../src/ext/standard/ftok.c \
../src/ext/standard/ftp_fopen_wrapper.c \
../src/ext/standard/head.c \
../src/ext/standard/html.c \
../src/ext/standard/http.c \
../src/ext/standard/http_fopen_wrapper.c \
../src/ext/standard/image.c \
../src/ext/standard/incomplete_class.c \
../src/ext/standard/info.c \
../src/ext/standard/iptc.c \
../src/ext/standard/lcg.c \
../src/ext/standard/levenshtein.c \
../src/ext/standard/link.c \
../src/ext/standard/link_win32.c \
../src/ext/standard/mail.c \
../src/ext/standard/math.c \
../src/ext/standard/md5.c \
../src/ext/standard/metaphone.c \
../src/ext/standard/microtime.c \
../src/ext/standard/pack.c \
../src/ext/standard/pageinfo.c \
../src/ext/standard/password.c \
../src/ext/standard/php_crypt_r.c \
../src/ext/standard/php_fopen_wrapper.c \
../src/ext/standard/proc_open.c \
../src/ext/standard/quot_print.c \
../src/ext/standard/rand.c \
../src/ext/standard/scanf.c \
../src/ext/standard/sha1.c \
../src/ext/standard/soundex.c \
../src/ext/standard/streamsfuncs.c \
../src/ext/standard/string.c \
../src/ext/standard/strnatcmp.c \
../src/ext/standard/syslog.c \
../src/ext/standard/type.c \
../src/ext/standard/uniqid.c \
../src/ext/standard/url.c \
../src/ext/standard/url_scanner_ex.c \
../src/ext/standard/user_filters.c \
../src/ext/standard/uuencode.c \
../src/ext/standard/var.c \
../src/ext/standard/var_unserializer.c \
../src/ext/standard/versioning.c 

O_SRCS += \
../src/ext/standard/array.o \
../src/ext/standard/assert.o \
../src/ext/standard/base64.o \
../src/ext/standard/basic_functions.o \
../src/ext/standard/browscap.o \
../src/ext/standard/crc32.o \
../src/ext/standard/credits.o \
../src/ext/standard/crypt.o \
../src/ext/standard/crypt_blowfish.o \
../src/ext/standard/crypt_freesec.o \
../src/ext/standard/crypt_sha256.o \
../src/ext/standard/crypt_sha512.o \
../src/ext/standard/css.o \
../src/ext/standard/cyr_convert.o \
../src/ext/standard/datetime.o \
../src/ext/standard/dir.o \
../src/ext/standard/dl.o \
../src/ext/standard/dns.o \
../src/ext/standard/exec.o \
../src/ext/standard/file.o \
../src/ext/standard/filestat.o \
../src/ext/standard/filters.o \
../src/ext/standard/flock_compat.o \
../src/ext/standard/formatted_print.o \
../src/ext/standard/fsock.o \
../src/ext/standard/ftok.o \
../src/ext/standard/ftp_fopen_wrapper.o \
../src/ext/standard/head.o \
../src/ext/standard/html.o \
../src/ext/standard/http.o \
../src/ext/standard/http_fopen_wrapper.o \
../src/ext/standard/image.o \
../src/ext/standard/incomplete_class.o \
../src/ext/standard/info.o \
../src/ext/standard/iptc.o \
../src/ext/standard/lcg.o \
../src/ext/standard/levenshtein.o \
../src/ext/standard/link.o \
../src/ext/standard/mail.o \
../src/ext/standard/math.o \
../src/ext/standard/md5.o \
../src/ext/standard/metaphone.o \
../src/ext/standard/microtime.o \
../src/ext/standard/pack.o \
../src/ext/standard/pageinfo.o \
../src/ext/standard/password.o \
../src/ext/standard/php_crypt_r.o \
../src/ext/standard/php_fopen_wrapper.o \
../src/ext/standard/proc_open.o \
../src/ext/standard/quot_print.o \
../src/ext/standard/rand.o \
../src/ext/standard/scanf.o \
../src/ext/standard/sha1.o \
../src/ext/standard/soundex.o \
../src/ext/standard/streamsfuncs.o \
../src/ext/standard/string.o \
../src/ext/standard/strnatcmp.o \
../src/ext/standard/syslog.o \
../src/ext/standard/type.o \
../src/ext/standard/uniqid.o \
../src/ext/standard/url.o \
../src/ext/standard/url_scanner_ex.o \
../src/ext/standard/user_filters.o \
../src/ext/standard/uuencode.o \
../src/ext/standard/var.o \
../src/ext/standard/var_unserializer.o \
../src/ext/standard/versioning.o 

OBJS += \
./src/ext/standard/array.o \
./src/ext/standard/assert.o \
./src/ext/standard/base64.o \
./src/ext/standard/basic_functions.o \
./src/ext/standard/browscap.o \
./src/ext/standard/crc32.o \
./src/ext/standard/credits.o \
./src/ext/standard/crypt.o \
./src/ext/standard/crypt_blowfish.o \
./src/ext/standard/crypt_freesec.o \
./src/ext/standard/crypt_sha256.o \
./src/ext/standard/crypt_sha512.o \
./src/ext/standard/css.o \
./src/ext/standard/cyr_convert.o \
./src/ext/standard/datetime.o \
./src/ext/standard/dir.o \
./src/ext/standard/dl.o \
./src/ext/standard/dns.o \
./src/ext/standard/dns_win32.o \
./src/ext/standard/exec.o \
./src/ext/standard/file.o \
./src/ext/standard/filestat.o \
./src/ext/standard/filters.o \
./src/ext/standard/flock_compat.o \
./src/ext/standard/formatted_print.o \
./src/ext/standard/fsock.o \
./src/ext/standard/ftok.o \
./src/ext/standard/ftp_fopen_wrapper.o \
./src/ext/standard/head.o \
./src/ext/standard/html.o \
./src/ext/standard/http.o \
./src/ext/standard/http_fopen_wrapper.o \
./src/ext/standard/image.o \
./src/ext/standard/incomplete_class.o \
./src/ext/standard/info.o \
./src/ext/standard/iptc.o \
./src/ext/standard/lcg.o \
./src/ext/standard/levenshtein.o \
./src/ext/standard/link.o \
./src/ext/standard/link_win32.o \
./src/ext/standard/mail.o \
./src/ext/standard/math.o \
./src/ext/standard/md5.o \
./src/ext/standard/metaphone.o \
./src/ext/standard/microtime.o \
./src/ext/standard/pack.o \
./src/ext/standard/pageinfo.o \
./src/ext/standard/password.o \
./src/ext/standard/php_crypt_r.o \
./src/ext/standard/php_fopen_wrapper.o \
./src/ext/standard/proc_open.o \
./src/ext/standard/quot_print.o \
./src/ext/standard/rand.o \
./src/ext/standard/scanf.o \
./src/ext/standard/sha1.o \
./src/ext/standard/soundex.o \
./src/ext/standard/streamsfuncs.o \
./src/ext/standard/string.o \
./src/ext/standard/strnatcmp.o \
./src/ext/standard/syslog.o \
./src/ext/standard/type.o \
./src/ext/standard/uniqid.o \
./src/ext/standard/url.o \
./src/ext/standard/url_scanner_ex.o \
./src/ext/standard/user_filters.o \
./src/ext/standard/uuencode.o \
./src/ext/standard/var.o \
./src/ext/standard/var_unserializer.o \
./src/ext/standard/versioning.o 

C_DEPS += \
./src/ext/standard/array.d \
./src/ext/standard/assert.d \
./src/ext/standard/base64.d \
./src/ext/standard/basic_functions.d \
./src/ext/standard/browscap.d \
./src/ext/standard/crc32.d \
./src/ext/standard/credits.d \
./src/ext/standard/crypt.d \
./src/ext/standard/crypt_blowfish.d \
./src/ext/standard/crypt_freesec.d \
./src/ext/standard/crypt_sha256.d \
./src/ext/standard/crypt_sha512.d \
./src/ext/standard/css.d \
./src/ext/standard/cyr_convert.d \
./src/ext/standard/datetime.d \
./src/ext/standard/dir.d \
./src/ext/standard/dl.d \
./src/ext/standard/dns.d \
./src/ext/standard/dns_win32.d \
./src/ext/standard/exec.d \
./src/ext/standard/file.d \
./src/ext/standard/filestat.d \
./src/ext/standard/filters.d \
./src/ext/standard/flock_compat.d \
./src/ext/standard/formatted_print.d \
./src/ext/standard/fsock.d \
./src/ext/standard/ftok.d \
./src/ext/standard/ftp_fopen_wrapper.d \
./src/ext/standard/head.d \
./src/ext/standard/html.d \
./src/ext/standard/http.d \
./src/ext/standard/http_fopen_wrapper.d \
./src/ext/standard/image.d \
./src/ext/standard/incomplete_class.d \
./src/ext/standard/info.d \
./src/ext/standard/iptc.d \
./src/ext/standard/lcg.d \
./src/ext/standard/levenshtein.d \
./src/ext/standard/link.d \
./src/ext/standard/link_win32.d \
./src/ext/standard/mail.d \
./src/ext/standard/math.d \
./src/ext/standard/md5.d \
./src/ext/standard/metaphone.d \
./src/ext/standard/microtime.d \
./src/ext/standard/pack.d \
./src/ext/standard/pageinfo.d \
./src/ext/standard/password.d \
./src/ext/standard/php_crypt_r.d \
./src/ext/standard/php_fopen_wrapper.d \
./src/ext/standard/proc_open.d \
./src/ext/standard/quot_print.d \
./src/ext/standard/rand.d \
./src/ext/standard/scanf.d \
./src/ext/standard/sha1.d \
./src/ext/standard/soundex.d \
./src/ext/standard/streamsfuncs.d \
./src/ext/standard/string.d \
./src/ext/standard/strnatcmp.d \
./src/ext/standard/syslog.d \
./src/ext/standard/type.d \
./src/ext/standard/uniqid.d \
./src/ext/standard/url.d \
./src/ext/standard/url_scanner_ex.d \
./src/ext/standard/user_filters.d \
./src/ext/standard/uuencode.d \
./src/ext/standard/var.d \
./src/ext/standard/var_unserializer.d \
./src/ext/standard/versioning.d 


# Each subdirectory must supply rules for building sources it contributes
src/ext/standard/%.o: ../src/ext/standard/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -O3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


